keys:
  - &blackbox age1r3dc5xkaz0s4rdaxnzh5thq3xmkwuddcvemw6uagppjvl7pxyvaqh0ky7f
  - &builder age1vxnqczfrhgn0h8zaeyetup6m66lc5cac8whs72c66ewz4qxjagvqx5ue7m
  - &donet age1tyw703k7tal82ehp4zhr6rzfrzhtv0s5cerwh2gedkt97pz4l4ksg2gykk
  - &epc age1773nn8we8n5yhn5qtneawstzw0wrhtd6zlkxvglj3tjgdlhc65tqllpjwl
  - &tuxedo age14keqxfdkualn3ez68y9flvspkyp4tqw43cn2sj6ar2tde5myc98qguqf8w
creation_rules:
  - path_regex: secrets/secrets.yaml
    key_groups:
      - age:
        - *blackbox
        - *donet
        - *epc
        - *tuxedo
  - path_regex: nixosModules/config/builder/secrets.yaml
    key_groups:
      - age:
        - *blackbox
        - *epc
        - *tuxedo
  - path_regex: nixosModules/config/nix/secrets.yaml
    key_groups:
      - age:
        - *blackbox
        - *builder
        - *donet
        - *epc
        - *tuxedo
  - path_regex: nixosModules/systems/builder/secrets.yaml
    key_groups:
      - age:
        - *builder
  - path_regex: nixosModules/systems/donet/secrets.yaml
    key_groups:
      - age:
        - *donet
        - *tuxedo
  - path_regex: nixosModules/users/nixos/secrets.yaml
    key_groups:
      - age:
        - *blackbox
        - *donet
        - *epc
        - *tuxedo
