keys:
  - &tuxedo age14keqxfdkualn3ez68y9flvspkyp4tqw43cn2sj6ar2tde5myc98qguqf8w
  - &blackbox age18xktg7kfy24t8tjnsnxqvdtrjysu30cfpthczh2t8ya7ng34c9nqrrwmrf
  - &epc age18xktg7kfy24t8tjnsnxqvdtrjysu30cfpthczh2t8ya7ng34c9nqrrwmrf
creation_rules:
  - path_regex: secrets/secrets.yaml
    key_groups:
      - age:
        - *tuxedo
        - *blackbox
        - *epc
  - path_regex: secrets/tuxedo.yaml
    key_groups:
      - age:
        - *tuxedo
  - path_regex: secrets/blackbox.yaml
    key_groups:
      - age:
        - *blackbox
  - path_regex: secrets/epc.yaml
    key_groups:
      - age:
        - *epc
