keys:
  - &tuxedo age14keqxfdkualn3ez68y9flvspkyp4tqw43cn2sj6ar2tde5myc98qguqf8w
  - &blackbox age1l5phd0krdnwdz626sjed3txgqgcug2l6ls3sgnqacke2pvsmfvlshtn9eh
  - &epc age1773nn8we8n5yhn5qtneawstzw0wrhtd6zlkxvglj3tjgdlhc65tqllpjwl
creation_rules:
  - path_regex: secrets/secrets.yaml
    key_groups:
      - age:
        - *tuxedo
        - *blackbox
        - *epc
  - path_regex: secrets/systems/blackbox.yaml
    key_groups:
      - age:
        - *blackbox
  - path_regex: secrets/systems/epc.yaml
    key_groups:
      - age:
        - *epc
