keys:
  - &tuxedo age14keqxfdkualn3ez68y9flvspkyp4tqw43cn2sj6ar2tde5myc98qguqf8w
  - &blackbox age1r3dc5xkaz0s4rdaxnzh5thq3xmkwuddcvemw6uagppjvl7pxyvaqh0ky7f
  - &epc age1773nn8we8n5yhn5qtneawstzw0wrhtd6zlkxvglj3tjgdlhc65tqllpjwl
creation_rules:
  - path_regex: secrets/secrets.yaml
    key_groups:
      - age:
        - *tuxedo
        - *blackbox
        - *epc
